### PR TITLE
Development

### PR DESCRIPTION
**Pull request by poonam9**
@rodica-andronache I have made flymag theme to woocommerce compatible. This is my first time to make things using hooks. Please let me know if any update is required.

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@poonam9 thanks, I will have a look :) First off, I don't understand why you removed this whole part http://prnt.sc/extiig  here https://github.com/Codeinwp/flymag/pull/39/commits/490334d0b22f4078a4a21139e38e287348f88a51

That was including the class-ti-about-page.php file and showing the About Flymag page

**Comment by rodica-andronache** [comment]
@poonam9 also, all functions and variables declared in the theme should be prefixed with the theme's slug, for example, you used woocommerce_support, this is very generic and should be something like flymag_woocommerce_support. Also, custom-woocommerce-style as a handle, should be prefixed with flymag too. 

And, I think you maybe just copied some code from shop isle, and replaced it with flymag, even though is not used. For example, you are calling flymag_do_shortcode which is not defined here, and some others functions/hooks. Can you please clean the code, and leave just what is needed? :D 
If you don't understand what a certain piece of code is doing, you can ask me. :)

**Comment by poonam9** [comment]
Thank you. I will try again with fresh code.

**Comment by rodica-andronache** [comment]
@poonam9 how is this going? Do you still plan to do this? :)

**Comment by poonam279** [comment]
@rodica-andronache I didn't get time to work on this but I still want to do this.

**Comment by rodica-andronache** [comment]
@poonam279 how is this going? :D

**Pull request closed without merging**
